name:                nzh
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/nzherald/ece-map#readme
license:             BSD3
author:              Chris Knox
maintainer:          chris.knox@nzherald.co.nz
copyright:           2020 NZ Herald 
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - cassava
  - cases
  - directory
  - filepath
  - foldl
  - megaparsec
  - modern-uri
  - monad-parallel
  - optparse-applicative
  - parser-combinators
  - req
  - split
  - scalpel
  - shake
  - tagsoup
  - text
  - time
  - unordered-containers
  - vector


library:
  source-dirs: src

executables:
  nzh:
    # ghc-options:  -Wall -threaded -rtsopts -with-rtsopts=-N
    source-dirs:      .
    main:             Shakefile.hs
    dependencies:
      - nzh
