name:                ece-map
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/vizowl/ece-map#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2020 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - cassava
  - directory
  - filepath
  - megaparsec
  - modern-uri
  - monad-parallel
  - optparse-applicative
  - parser-combinators
  - req
  - split
  - scalpel
  - tagsoup
  - text
  - time
  - vector

ghc-options:  -Wall -threaded -rtsopts -with-rtsopts=-N

executables:
  ece-map:
    source-dirs:      src
    main:             Main.hs
